--liquibase formatted sql

--changeset mturra:201901301231_215 runOnChange:true stripComments:false endDelimiter:/


CREATE OR REPLACE PACKAGE Amv_Menu_Pac IS
/******************************************************************************
 NOME:        menu_pac.
 DESCRIZIONE: .
 ANNOTAZIONI:
 REVISIONI:
 Rev. Data       Autore Descrizione
 ---- ---------- ------ ------------------------------------------------------
 0    22/09/2005 AO     Creazione.
******************************************************************************/
TYPE voci_rc IS REF CURSOR;
TYPE guide_rc IS REF CURSOR;

FUNCTION VERSIONE RETURN VARCHAR2;

PROCEDURE VOCI_PD(
  P_UTENTE IN VARCHAR2
, P_VOCE IN VARCHAR2
);

PROCEDURE VOCI_PIU  (
  P_UTENTE IN VARCHAR2
, P_INSERT_UPDATE IN VARCHAR2
, P_VOCE IN VARCHAR2
, P_PROGETTO IN VARCHAR2
, P_ACRONIMO IN VARCHAR2
, P_ACRONIMO_AL1 IN VARCHAR2
, P_ACRONIMO_AL2 IN VARCHAR2
, P_TITOLO IN VARCHAR2
, P_TITOLO_AL1 IN VARCHAR2
, P_TITOLO_AL2 IN VARCHAR2
, P_TIPO_VOCE IN VARCHAR2
, P_TIPO IN VARCHAR2
, P_MODULO IN VARCHAR2
, P_STRINGA IN VARCHAR2
, P_PROFILO IN VARCHAR2
, P_VOCE_GUIDA IN VARCHAR2
, P_PROPRIETA IN VARCHAR2
, P_NOTE IN VARCHAR2
, P_PADRE IN NUMBER
, P_PADRE_OLD IN NUMBER
, P_ABIL_MODULO IN VARCHAR2
, P_SEQUENZA IN NUMBER
, P_RUOLO IN VARCHAR2
, P_ABILITAZIONI IN NUMBER
, P_VOCE_OLD IN VARCHAR2
);

FUNCTION GET_ALBERO_MENU
( P_USER      IN VARCHAR2
, P_UTENTE    IN  VARCHAR2
, P_ISTANZA   IN  VARCHAR2
, P_MODULO    IN  VARCHAR2
, P_PROGETTO  IN  VARCHAR2
, P_VOCE_L2   IN  VARCHAR2
, P_VOCE_L3   IN  VARCHAR2
, P_RUOLO     IN  VARCHAR2
, P_VOCE_SEL  IN  VARCHAR2
, P_ID        IN  VARCHAR2
) RETURN CLOB;

FUNCTION get_voce_rc
( p_user     IN VARCHAR2
, p_voce     IN VARCHAR2
, p_modulo   IN VARCHAR2
, p_ruolo    IN VARCHAR2
, p_padre    IN VARCHAR2
)
RETURN voci_rc;

FUNCTION get_voci_guida_rc
( p_user     IN VARCHAR2
, p_progetto IN VARCHAR2
)
RETURN voci_rc;

FUNCTION get_voci_padre_rc
( p_user     IN VARCHAR2
, p_modulo   IN VARCHAR2
)
RETURN voci_rc;

PROCEDURE GUIDE_PD(
  P_USER  IN VARCHAR2
, P_GUIDA IN VARCHAR2
, P_SEQUENZA IN NUMBER
);

PROCEDURE GUIDA_PIU  (
  P_USER IN VARCHAR2
, P_INSERT_UPDATE IN VARCHAR2
, P_GUIDA IN VARCHAR2
, P_SEQUENZA IN NUMBER
, P_ALIAS IN VARCHAR2
, P_TITOLO IN VARCHAR2
, P_VOCE_MENU  IN VARCHAR2
, P_VOCE_RIF IN VARCHAR2
);

FUNCTION get_guida_rc
( p_user     IN VARCHAR2
, p_guida    IN VARCHAR2
, p_sequenza IN VARCHAR2
)
RETURN guide_rc;

FUNCTION get_guide_rc
( p_user        IN VARCHAR2
, p_id          IN VARCHAR2
, p_id_sessione IN VARCHAR2
)
RETURN guide_rc;
END Amv_Menu_Pac;
/