--liquibase formatted sql

--changeset mturra:201901301231_245 runOnChange:true stripComments:false endDelimiter:/

create or replace package istanza_amm_pkg is
/******************************************************************************
 NOME:        istanze_amm_pkg
 DESCRIZIONE: Gestione tabella ISTANZE.
 ANNOTAZIONI: .
 REVISIONI:
 <CODE>
 Rev.  Data       Autore  Descrizione.
 00    24/07/2007  MMalferrari  Prima emissione.
******************************************************************************/
   -- Revisione del Package
   s_revisione constant AFC.t_revision := 'V1.00';
   -- Versione e revisione
   function versione
   return varchar2;
   function get_istanza_ad4
   return ISTANZE.istanza%type;
   -- Attributo ISTANZA_AMMINISTRATORE di riga esistente identificata da chiave
   FUNCTION get_ISTANZA_AMMINISTRATORE
   ( p_DATABASE_USER  IN ISTANZE.USER_ORACLE%TYPE
   , p_ISTANZA IN ISTANZE.ISTANZA%TYPE DEFAULT NULL
   ) RETURN ISTANZE.ISTANZA_AMMINISTRATORE%TYPE;
   -- Verifica se l'istanza e' un istanza di amministratore.
   function is_istanza_amministratore
   (
    p_istanza  in ISTANZE.istanza%type
   ) return number;
   -- Inserimento di una riga e commit
   PROCEDURE ins_commit
   ( p_ISTANZA  IN ISTANZE.Istanza%TYPE
   , p_PROGETTO  IN ISTANZE.PROGETTO%TYPE
   , p_ENTE  IN ISTANZE.ENTE%TYPE
   , p_DESCRIZIONE  IN ISTANZE.DESCRIZIONE%TYPE
   , p_DATABASE_USER IN ISTANZE.USER_ORACLE%TYPE
   , p_DATABASE_PASSWORD IN ISTANZE.PASSWORD_ORACLE%TYPE
   , p_DISLOCAZIONE  IN ISTANZE.DISLOCAZIONE%TYPE
   , p_DISLOCAZIONE_TEMPORANEA  IN ISTANZE.DISLOCAZIONE_TEMPORANEA%TYPE  DEFAULT NULL
   , p_INSTALLAZIONE  IN ISTANZE.INSTALLAZIONE%TYPE  DEFAULT NULL
   , p_VERSIONE  IN ISTANZE.VERSIONE%TYPE  DEFAULT NULL
   , p_DISLOCAZIONE_DIMENSIONAMENTI  IN ISTANZE.DISLOCAZIONE_DIMENSIONAMENTI%TYPE  DEFAULT NULL
   , p_NOTE  IN ISTANZE.NOTE%TYPE  DEFAULT NULL
   , p_LINGUA  IN ISTANZE.LINGUA%TYPE  DEFAULT 'I'
   , p_LINK_ORACLE  IN ISTANZE.LINK_ORACLE%TYPE  DEFAULT NULL
   , p_DATABASE_LINK  IN ISTANZE.DATABASE_LINK%TYPE  DEFAULT NULL
   , p_DATABASE_DRIVER  IN ISTANZE.DATABASE_DRIVER%TYPE  DEFAULT NULL
   , p_SERVIZIO  IN ISTANZE.SERVIZIO%TYPE  DEFAULT NULL
   , p_ISTANZA_AMMINISTRATORE IN ISTANZE.ISTANZA_AMMINISTRATORE%TYPE  DEFAULT NULL
   );
   -- Aggiornamento di una riga e commit
   PROCEDURE upd_commit
   ( p_NEW_ISTANZA  IN ISTANZE .Istanza%TYPE
   , p_NEW_PROGETTO  IN ISTANZE.PROGETTO%TYPE DEFAULT NULL
   , p_NEW_ENTE  IN ISTANZE.ENTE%TYPE DEFAULT NULL
   , p_NEW_DESCRIZIONE  IN ISTANZE.DESCRIZIONE%TYPE DEFAULT NULL
   , p_NEW_DATABASE_USER IN ISTANZE.USER_ORACLE%TYPE DEFAULT NULL
   , p_NEW_DATABASE_PASSWORD IN ISTANZE.PASSWORD_ORACLE%TYPE DEFAULT NULL
   , p_NEW_DISLOCAZIONE  IN ISTANZE.DISLOCAZIONE%TYPE DEFAULT NULL
   , p_NEW_DISLOCAZIONE_TEMPORANEA  IN ISTANZE.DISLOCAZIONE_TEMPORANEA%TYPE DEFAULT NULL
   , p_NEW_INSTALLAZIONE  IN ISTANZE.INSTALLAZIONE%TYPE DEFAULT NULL
   , p_NEW_VERSIONE  IN ISTANZE.VERSIONE%TYPE DEFAULT NULL
   , p_NEW_DISL_DIMENSIONAMENTI  IN ISTANZE.DISLOCAZIONE_DIMENSIONAMENTI%TYPE DEFAULT NULL
   , p_NEW_NOTE  IN ISTANZE.NOTE%TYPE  DEFAULT NULL
   , p_NEW_LINGUA  IN ISTANZE.LINGUA%TYPE DEFAULT 'I'
   , p_NEW_LINK_ORACLE  IN ISTANZE.LINK_ORACLE%TYPE  DEFAULT NULL
   , p_NEW_DATABASE_LINK  IN ISTANZE.DATABASE_LINK%TYPE  DEFAULT NULL
   , p_NEW_DATABASE_DRIVER  IN ISTANZE.DATABASE_DRIVER%TYPE  DEFAULT NULL
   , p_NEW_SERVIZIO  IN ISTANZE.SERVIZIO%TYPE  DEFAULT NULL
   , p_NEW_ISTANZA_AMMINISTRATORE IN ISTANZE.ISTANZA_AMMINISTRATORE%TYPE  DEFAULT NULL
   , p_OLD_ISTANZA  IN ISTANZE.Istanza%TYPE DEFAULT NULL
   , p_OLD_ISTANZA_AMMINISTRATORE IN ISTANZE.ISTANZA_AMMINISTRATORE%TYPE  DEFAULT NULL
   );
   PROCEDURE del_commit
         ( p_ISTANZA  IN ISTANZE.Istanza%TYPE
         , p_DATABASE_USER IN ISTANZE.USER_ORACLE%TYPE
         , p_ISTANZA_AMMINISTRATORE IN ISTANZE.ISTANZA_AMMINISTRATORE%TYPE
         );
   function get_log
   return clob;
   procedure add_log ( p_log in varchar2 );
   FUNCTION count_database_user
   ( p_DATABASE_USER   IN ISTANZE.USER_ORACLE%TYPE
   , p_ISTANZA IN ISTANZE.ISTANZA%TYPE DEFAULT NULL
   ) RETURN INTEGER;
end istanza_amm_pkg;
/