CREATE TABLE AD4_LDAP_ATTRIBUTI
(
  DN                VARCHAR2(4000 BYTE),
  NOME_ATTRIBUTO    VARCHAR2(100 BYTE),
  VALORE_ATTRIBUTO  VARCHAR2(4000 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


