CREATE TABLE AD4_LDAP_STRUTTURA
(
  DN           VARCHAR2(4000 BYTE),
  TIPO         VARCHAR2(18 BYTE),
  DESCRIZIONE  VARCHAR2(4000 BYTE),
  FIGLIO       VARCHAR2(8 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


