CREATE TABLE ANAG_UNITA
(
  AMMINISTRAZIONE            VARCHAR2(16 BYTE),
  CODICE_UO                  VARCHAR2(16 BYTE),
  DES_UNITA_ORGANIZZATIVA    VARCHAR2(120 BYTE),
  DES_ABB                    VARCHAR2(20 BYTE),
  UTENTE_AD4                 VARCHAR2(8 BYTE),
  CODICE_AOO                 VARCHAR2(4000 BYTE),
  PROGR_AOO                  NUMBER(8),
  PROGR_UNITA_ORGANIZZATIVA  NUMBER(8)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


