CREATE TABLE ASSISTENTE_VIRTUALE
(
  ID                   NUMBER,
  AREA_APPLICATIVA     VARCHAR2(20 BYTE)        NOT NULL,
  MODULO_SOFTWARE      VARCHAR2(10 BYTE)        NOT NULL,
  PAGINA_APPLICATIVA   VARCHAR2(40 BYTE)        NOT NULL,
  LINK                 VARCHAR2(200 BYTE)       NOT NULL,
  VERSIONE_ASSISTENTE  VARCHAR2(10 BYTE),
  LINGUA               VARCHAR2(1 BYTE),
  VERSION              NUMBER
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE ASSISTENTE_VIRTUALE IS 'ASVI - Tabella con i link ai manuali ';



