CREATE TABLE CARATTERISTICHE_ACC_STORICO
(
  ID_EVENTO                 NUMBER              NOT NULL,
  CAAC_ID                   NUMBER,
  TIPO_ACCESSO              VARCHAR2(1 BYTE),
  PROGETTO                  VARCHAR2(8 BYTE),
  ISTANZA                   VARCHAR2(10 BYTE),
  MODULO                    VARCHAR2(10 BYTE),
  UTENTE                    VARCHAR2(8 BYTE),
  ACCESSO                   VARCHAR2(1 BYTE),
  ACCESSO_SE                VARCHAR2(2 BYTE),
  TRACCIA                   VARCHAR2(1 BYTE),
  GIORNI_TRACCIA            NUMBER(3),
  TENTATIVI_PASSWORD        NUMBER(2),
  VALIDITA_PASSWORD         NUMBER(3),
  SINGLE_SIGN_ON            VARCHAR2(2 BYTE),
  SLEEP                     NUMBER,
  LDAP                      VARCHAR2(2 BYTE),
  MIN_LUNGHEZZA_PWD         NUMBER(2),
  MOD_PWD_PRIMO_ACCESSO     VARCHAR2(2 BYTE),
  ARCHIVIAZIONE_TRACCIA     VARCHAR2(2 BYTE),
  DISLOCAZIONE_TRACCIA      VARCHAR2(100 BYTE),
  AMMESSI_CAR_SPECIALI_PWD  VARCHAR2(2 BYTE),
  NUMERI_OBB_PWD            VARCHAR2(2 BYTE),
  GG_PRIMA_RIUTILIZZO_PWD   NUMBER(3),
  DATA                      DATE,
  OPERAZIONE                VARCHAR2(2 BYTE),
  BI_RIFERIMENTO            NUMBER,
  UTENTE_AGGIORNAMENTO      VARCHAR2(8 BYTE),
  USER_ORACLE               VARCHAR2(30 BYTE),
  INFO                      VARCHAR2(2000 BYTE),
  PROGRAMMA                 VARCHAR2(50 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE CARATTERISTICHE_ACC_STORICO IS 'CAAS -CARATTERISTICHE ACCESSO STORICO';

COMMENT ON COLUMN CARATTERISTICHE_ACC_STORICO.OPERAZIONE IS 'I=Insert, D=Delete, BI=Before Image, AI=After Image';



