CREATE TABLE COMUNI_NEW
(
  PROVINCIA_STATO          NUMBER(3)            NOT NULL,
  COMUNE                   NUMBER(3)            NOT NULL,
  DENOMINAZIONE            VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL1        VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL2        VARCHAR2(40 BYTE),
  DENOMINAZIONE_BREVE      VARCHAR2(16 BYTE),
  DENOMINAZIONE_BREVE_AL1  VARCHAR2(16 BYTE),
  DENOMINAZIONE_BREVE_AL2  VARCHAR2(16 BYTE),
  CAPOLUOGO_PROVINCIA      VARCHAR2(1 BYTE),
  CAP                      NUMBER(5),
  PROVINCIA_TRIBUNALE      NUMBER(3),
  COMUNE_TRIBUNALE         NUMBER(3),
  PROVINCIA_DISTRETTO      NUMBER(3),
  COMUNE_DISTRETTO         NUMBER(3),
  DATA_SOPPRESSIONE        DATE,
  PROVINCIA_FUSIONE        NUMBER(3),
  COMUNE_FUSIONE           NUMBER(3),
  SIGLA_CFIS               VARCHAR2(4 BYTE),
  CONSOLATO                NUMBER(5),
  TIPO_CONSOLATO           NUMBER(2),
  UTENTE_AGGIORNAMENTO     VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO       DATE,
  DATA_ISTITUZIONE         DATE
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


