CREATE TABLE CREDENZIALI_LIVELLO
(
  LIVELLO           VARCHAR2(8 BYTE)            NOT NULL,
  TIPO_CREDENZIALE  VARCHAR2(8 BYTE)            NOT NULL
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


