CREATE TABLE INFORMATIVE_PRIVACY
(
  ID                     NUMBER                 NOT NULL,
  ENTE                   VARCHAR2(4 BYTE),
  MODULO                 VARCHAR2(10 BYTE),
  DATA_INFORMATIVA       DATE,
  URL_DOCUMENTO_PRIVACY  VARCHAR2(2000 BYTE),
  NOTE                   VARCHAR2(2000 BYTE),
  CHIAVE_PRIVACY         VARCHAR2(60 BYTE),
  URL_NOTE_LEGALI        VARCHAR2(2000 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE INFORMATIVE_PRIVACY IS 'INPY - Informative Privacy';



