CREATE TABLE LDAP_ATTRIBUTI
(
  ID_DN             NUMBER                      NOT NULL,
  NOME_ATTRIBUTO    VARCHAR2(4000 BYTE)         NOT NULL,
  VALORE_ATTRIBUTO  VARCHAR2(4000 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


