CREATE TABLE MODULI
(
  MODULO           VARCHAR2(10 BYTE)            NOT NULL,
  DESCRIZIONE      VARCHAR2(40 BYTE)            NOT NULL,
  DESCRIZIONE_AL1  VARCHAR2(40 BYTE),
  DESCRIZIONE_AL2  VARCHAR2(40 BYTE),
  PROGETTO         VARCHAR2(8 BYTE)             NOT NULL,
  NOTE             VARCHAR2(2000 BYTE),
  AMMINISTRATORE   VARCHAR2(1 BYTE)             DEFAULT 'N'
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE MODULI IS 'MODU - Tabella dei moduli applicativi';

COMMENT ON COLUMN MODULI.DESCRIZIONE IS 'Descrizione MODULO <NLS>';

COMMENT ON COLUMN MODULI.AMMINISTRATORE IS 'Indica se modulo  utilizzato per funzioni di AMMINISTRAZIONE';



