CREATE TABLE PARAMETRI_RICHIESTA
(
  ID_PARAMETRO          NUMBER                  NOT NULL,
  ID_RICHIESTA          NUMBER                  NOT NULL,
  PARAMETRO             VARCHAR2(60 BYTE)       NOT NULL,
  VALORE                VARCHAR2(2000 BYTE),
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


