CREATE TABLE PROVINCE_STORICO
(
  PROVINCIA             NUMBER(3)               NOT NULL,
  DENOMINAZIONE         VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL1     VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL2     VARCHAR2(40 BYTE),
  REGIONE               NUMBER(3),
  SIGLA                 VARCHAR2(2 BYTE)        NOT NULL,
  DATA_ISTITUZIONE      DATE,
  DATA_INIZIO_VALIDITA  DATE,
  DATA_FINE_VALIDITA    DATE,
  FLAG_ISTAT            VARCHAR2(1 BYTE),
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE PROVINCE_STORICO IS 'PRST - Storico delle province italiane';

COMMENT ON COLUMN PROVINCE_STORICO.PROVINCIA IS 'Codice della provincia';

COMMENT ON COLUMN PROVINCE_STORICO.DENOMINAZIONE IS 'Dominazione della provincia';

COMMENT ON COLUMN PROVINCE_STORICO.DENOMINAZIONE_AL1 IS 'Dominazione della provincia';

COMMENT ON COLUMN PROVINCE_STORICO.DENOMINAZIONE_AL2 IS 'Dominazione della provincia';

COMMENT ON COLUMN PROVINCE_STORICO.REGIONE IS 'Codice regione';

COMMENT ON COLUMN PROVINCE_STORICO.SIGLA IS 'Sigla automobilistica';



