CREATE TABLE RAGGRUPPAMENTI_STATI_NEW
(
  RAGGRUPPAMENTO        NUMBER(2)               NOT NULL,
  DESCRIZIONE           VARCHAR2(40 BYTE),
  DESCRIZIONE_AL1       VARCHAR2(40 BYTE),
  DESCRIZIONE_AL2       VARCHAR2(40 BYTE),
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


