CREATE TABLE STATI_TERRITORI_NEW
(
  STATO_TERRITORIO       NUMBER(3)              NOT NULL,
  DENOMINAZIONE          VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL1      VARCHAR2(40 BYTE),
  DENOMINAZIONE_AL2      VARCHAR2(40 BYTE),
  SIGLA                  VARCHAR2(5 BYTE),
  DESC_CITTADINANZA      VARCHAR2(40 BYTE),
  DESC_CITTADINANZA_AL1  VARCHAR2(40 BYTE),
  DESC_CITTADINANZA_AL2  VARCHAR2(40 BYTE),
  RAGGRUPPAMENTO         NUMBER(2),
  STATO_APPARTENENZA     NUMBER(3),
  UTENTE_AGGIORNAMENTO   VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO     DATE,
  SIGLA_ISO3166_ALPHA2   VARCHAR2(2 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


