CREATE TABLE STRUTTURA_UTENTI_TEMP
(
  DESCRIZIONE  VARCHAR2(4000 BYTE),
  FIGLIO       VARCHAR2(8 BYTE),
  TIPO_FIGLIO  VARCHAR2(1 BYTE),
  PADRE        VARCHAR2(8 BYTE),
  TIPO_PADRE   VARCHAR2(1 BYTE),
  STRUTTURA    VARCHAR2(4000 BYTE),
  LIVELLO      NUMBER,
  ORD          VARCHAR2(4000 BYTE),
  GRUPPO_SO    VARCHAR2(1 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


