CREATE TABLE TIPI_CREDENZIALE
(
  TIPO_CREDENZIALE  VARCHAR2(8 BYTE)            NOT NULL,
  DESCRIZIONE       VARCHAR2(40 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN TIPI_CREDENZIALE.DESCRIZIONE IS 'Descrizione TIPO di CREDENZIALE <NLS>';



