CREATE TABLE UTENTI_SOGGETTI_STORICO
(
  ID_EVENTO       NUMBER                        NOT NULL,
  UTENTE          VARCHAR2(8 BYTE)              NOT NULL,
  SOGGETTO        NUMBER                        NOT NULL,
  DATA            DATE                          NOT NULL,
  OPERAZIONE      VARCHAR2(2 BYTE),
  BI_RIFERIMENTO  NUMBER,
  UTENTE_AGG      VARCHAR2(8 BYTE),
  USER_ORACLE     VARCHAR2(30 BYTE),
  INFO            VARCHAR2(2000 BYTE),
  PROGRAMMA       VARCHAR2(50 BYTE)
)
TABLESPACE AD4
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE UTENTI_SOGGETTI_STORICO IS 'UTSS - UTENTI SOGGETTI STORICO';

COMMENT ON COLUMN UTENTI_SOGGETTI_STORICO.OPERAZIONE IS 'I=Insert, D=Delete, BI=Before Image, AI=After Image';

COMMENT ON COLUMN UTENTI_SOGGETTI_STORICO.BI_RIFERIMENTO IS 'id_evento di Before Image di riferimento';



