CREATE OR REPLACE FORCE VIEW GRUPPI_LAVORO
(GRUPPO_LAVORO, DESCRIZIONE, DESCRIZIONE_AL1, DESCRIZIONE_AL2)
BEQUEATH DEFINER
AS 
SELECT ruolo, descrizione, descrizione_al1, descrizione_al2
  FROM RUOLI
 WHERE GRUPPO_LAVORO = 'S'
   AND stato = 'U';


