CREATE INDEX AD4_LDST_FIGLIO_IK ON AD4_LDAP_STRUTTURA
(FIGLIO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


