CREATE UNIQUE INDEX AMV_DOCUMENTI_REVISIONI_PK ON AMV_DOCUMENTI_REVISIONI
(ID_DOCUMENTO, REVISIONE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


