CREATE INDEX AMV_DOCU_REVI_UTEN_RED ON AMV_DOCUMENTI_REVISIONI
(UTENTE_REDAZIONE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


