CREATE UNIQUE INDEX ASVI_PK ON ASSISTENTE_VIRTUALE
(ID)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


