CREATE INDEX ASVI_AREA_MODU_PAGI_IK ON ASSISTENTE_VIRTUALE
(AREA_APPLICATIVA, MODULO_SOFTWARE, PAGINA_APPLICATIVA)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


