CREATE UNIQUE INDEX CAAC_UK ON CARATTERISTICHE_ACCESSO
(TIPO_ACCESSO, PROGETTO, ISTANZA, MODULO, UTENTE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


