CREATE UNIQUE INDEX CODIFICA_ISTAT_UK ON PAESI_TERRITORI_AG_ENTRATE
(CODIFICA_ISTAT)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


