CREATE INDEX CREDENZIALI_UTENTE_UTEN_FK ON CREDENZIALI_UTENTE
(UTENTE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


