CREATE UNIQUE INDEX CREDENZIALI_LIVELLO_PK ON CREDENZIALI_LIVELLO
(LIVELLO, TIPO_CREDENZIALE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


