CREATE INDEX DIAS_IK ON DIRITTI_ACCESSO_STORICO
(UTENTE, MODULO, ISTANZA, RUOLO, DATA, 
OPERAZIONE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


