CREATE UNIQUE INDEX DISA_PK ON DISABILITAZIONI
(RUOLO, MODULO, WINDOW)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


