CREATE UNIQUE INDEX LDST_PK ON LDAP_STRUTTURA
(ID_DN)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


