CREATE UNIQUE INDEX LISI_PK ON LIVELLI_SICUREZZA
(LIVELLO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


