CREATE UNIQUE INDEX OMONIMIE_GESTITE_PK ON OMONIMIE_GESTITE
(ID_OMONIMIA)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


