CREATE UNIQUE INDEX OMONIMIE_GESTITKE_UK ON OMONIMIE_GESTITE
(PRIMARIO, SECONDARIO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


