CREATE UNIQUE INDEX PAESI_TERRITORI_AG_ENTRATE_PK ON PAESI_TERRITORI_AG_ENTRATE
(DENOMINAZIONE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


