CREATE UNIQUE INDEX PARI_PK ON PARAMETRI_RICHIESTA
(ID_PARAMETRO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


