CREATE UNIQUE INDEX PERS_PK ON PERSONALIZZAZIONI
(MODULO, ENTE, WINDOW)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


