CREATE UNIQUE INDEX RIAB_PK ON RICHIESTE_ABILITAZIONE
(ID_RICHIESTA)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


