CREATE UNIQUE INDEX SI4_USER_SOURCE_PK ON SI4_USER_SOURCE
(NAME, TYPE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


