CREATE UNIQUE INDEX SI4_USER_SOURCE_FILENAME_UK ON SI4_USER_SOURCE
(FILENAME)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


