CREATE UNIQUE INDEX SOGG_PK ON SOGGETTI_OLD
(SOGGETTO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


