CREATE UNIQUE INDEX STTS_PK ON STATI_TERRITORI_STORICO
(STATO_TERRITORIO, DATA_INIZIO_VALIDITA)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


