CREATE INDEX STUT_TMP_TIPO_FIGLIO_IK ON STRUTTURA_UTENTI_TEMP
(TIPO_FIGLIO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


