CREATE UNIQUE INDEX UTENTI_PRIVACY_UK ON UTENTI_PRIVACY
(UTENTE, ENTE, MODULO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


