CREATE INDEX UTSO_SOGGETTO_IK ON UTENTI_SOGGETTI
(SOGGETTO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


