CREATE UNIQUE INDEX UTSS_PK ON UTENTI_SOGGETTI_STORICO
(ID_EVENTO)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


