CREATE INDEX UTSS_UTENTE_IK ON UTENTI_SOGGETTI_STORICO
(UTENTE)
TABLESPACE AD4
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


