ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_ACCE_CC
  CHECK (
            ACCESSO is null or (ACCESSO in ('I','U','S','L')))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_ACCESSO_SE_CC
  CHECK (
            ACCESSO_SE is null or (ACCESSO_SE in ('SI','NO')))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_AMMESSI_CAR_SPECIALI_PWD
  CHECK (AMMESSI_CAR_SPECIALI_PWD IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_ARCHIVIAZIONE_TRACCIA
  CHECK (ARCHIVIAZIONE_TRACCIA IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_LDAP
  CHECK (LDAP IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_MIN_LUNGHEZZA_PWD
  CHECK (MIN_LUNGHEZZA_PWD >= 0 )
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_MOD_PWD_PRIMO_ACCESSO
  CHECK (MOD_PWD_PRIMO_ACCESSO IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_NUMERI_OBB_PWD
  CHECK (numeri_obb_pwd IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_TIPO_ACCESSO_CC
  CHECK (TIPO_ACCESSO in ('D','M','G','I','P'))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_TRACCIA_CC
  CHECK (TRACCIA is null or (TRACCIA in ('M','F','I')))
  ENABLE VALIDATE);

ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_PK
  PRIMARY KEY
  (CAAC_ID)
  USING INDEX CAAC_PK
  ENABLE VALIDATE);

