ALTER TABLE CARATTERISTICHE_ACCESSO ADD (
  CONSTRAINT CAAC_DIAC_FK 
  FOREIGN KEY (UTENTE, MODULO, ISTANZA) 
  REFERENCES DIRITTI_ACCESSO (UTENTE,MODULO,ISTANZA)
  ON DELETE CASCADE
  ENABLE VALIDATE);

