ALTER TABLE CREDENZIALI_UTENTE ADD (
  CONSTRAINT CRED_CRUN_FK 
  FOREIGN KEY (ID_CREDENZIALE) 
  REFERENCES CREDENZIALI (ID_CREDENZIALE)
  ENABLE VALIDATE);

ALTER TABLE CREDENZIALI_UTENTE ADD (
  CONSTRAINT UTEN_CRUN_FK 
  FOREIGN KEY (UTENTE) 
  REFERENCES UTENTI (UTENTE)
  ENABLE VALIDATE);

