ALTER TABLE CREDENZIALI ADD (
  CONSTRAINT CRED_STATO_CC
  CHECK (STATO in ('U','S','R'))
  ENABLE VALIDATE);

ALTER TABLE CREDENZIALI ADD (
  CONSTRAINT CRED_PK
  PRIMARY KEY
  (ID_CREDENZIALE)
  USING INDEX CRED_PK
  ENABLE VALIDATE);

ALTER TABLE CREDENZIALI ADD (
  CONSTRAINT CRED_CHIAVE_AK
  UNIQUE (CHIAVE_CREDENZIALE)
  USING INDEX CRED_CHIAVE_AK
  ENABLE VALIDATE);

