ALTER TABLE CREDENZIALI_LIVELLO ADD (
  CONSTRAINT LISI_CRLI_FK 
  FOREIGN KEY (LIVELLO) 
  REFERENCES LIVELLI_SICUREZZA (LIVELLO)
  ENABLE VALIDATE);

ALTER TABLE CREDENZIALI_LIVELLO ADD (
  CONSTRAINT TICR_CRLI_FK 
  FOREIGN KEY (TIPO_CREDENZIALE) 
  REFERENCES TIPI_CREDENZIALE (TIPO_CREDENZIALE)
  ENABLE VALIDATE);

