ALTER TABLE DIRITTI_ACCESSO_STORICO ADD (
  CONSTRAINT DIAS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE DIRITTI_ACCESSO_STORICO ADD (
  CONSTRAINT DIAS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX DIAS_PK
  ENABLE VALIDATE);

