ALTER TABLE INFORMATIVE_PRIVACY ADD (
  CONSTRAINT INFORMATIVE_PRIVACY_PK
  PRIMARY KEY
  (ID)
  USING INDEX INFORMATIVE_PRIVACY_PK
  ENABLE VALIDATE);

ALTER TABLE INFORMATIVE_PRIVACY ADD (
  CONSTRAINT INFORMATIVE_PRIVACY_UK
  UNIQUE (ENTE, MODULO, CHIAVE_PRIVACY)
  USING INDEX INFORMATIVE_PRIVACY_UK
  ENABLE VALIDATE);

