ALTER TABLE ISTANZE_STORICO ADD (
  CONSTRAINT ISST_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE ISTANZE_STORICO ADD (
  CONSTRAINT ISST_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX ISST_PK
  ENABLE VALIDATE);

