ALTER TABLE LDAP_STRUTTURA ADD (
  CONSTRAINT LDAP_STRUTTURA_CATEGORIA_CC
  CHECK (categoria in ('PERSON','GROUP','ORGANIZATIONALUNIT','DOMAIN','CONTAINER','OTHER'))
  ENABLE VALIDATE);

ALTER TABLE LDAP_STRUTTURA ADD (
  CONSTRAINT LDST_PK
  PRIMARY KEY
  (ID_DN)
  USING INDEX LDST_PK
  ENABLE VALIDATE);

