ALTER TABLE MODULI ADD (
  CONSTRAINT MODU_AMM_CK
  CHECK (amministratore in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE MODULI ADD (
  CONSTRAINT MODU_PK
  PRIMARY KEY
  (MODULO)
  USING INDEX MODU_PK
  ENABLE VALIDATE);

