ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOLI_GRUPPO_LAVORO_CC
  CHECK (GRUPPO_LAVORO IN ('S', 'N'))
  ENABLE VALIDATE);

ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOLI_GRUPPO_SO_CC
  CHECK (GRUPPO_SO IN ('S', 'N'))
  ENABLE VALIDATE);

ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOLI_INCARICO_CC
  CHECK (INCARICO IN ('S', 'N'))
  ENABLE VALIDATE);

ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOLI_RESPONSABILITA_CC
  CHECK (RESPONSABILITA IN ('S', 'N'))
  ENABLE VALIDATE);

ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOLI_STATO_CC
  CHECK (stato IN ('U', 'R'))
  ENABLE VALIDATE);

ALTER TABLE RUOLI ADD (
  CONSTRAINT RUOL_PK
  PRIMARY KEY
  (RUOLO)
  USING INDEX RUOL_PK
  ENABLE VALIDATE);

