ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERVIZI_ABILITAZIONE_CC
  CHECK (ABILITAZIONE in ('A','C'))
  ENABLE VALIDATE);

ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERVIZI_MULTIPLO_CC
  CHECK (MULTIPLO in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERVIZI_RECUPERO_PASSWORD_CC
  CHECK (RECUPERO_PASSWORD IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERVIZI_TIPO_NOTIFICA_CC
  CHECK (TIPO_NOTIFICA is null or (TIPO_NOTIFICA in ('MAIL','POSTA','SMS','FAX')))
  ENABLE VALIDATE);

ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERV_PK
  PRIMARY KEY
  (ID_SERVIZIO)
  USING INDEX SERV_PK
  ENABLE VALIDATE);

ALTER TABLE SERVIZI ADD (
  CONSTRAINT SERV_AK
  UNIQUE (ISTANZA, MODULO)
  USING INDEX SERV_AK
  ENABLE VALIDATE);

