ALTER TABLE SI4_USER_SOURCE ADD (
  CONSTRAINT SI4_USER_SOUR_TYPE_CC
  CHECK (TYPE in ('PROCEDURE','FUNCTION','PACKAGE','PACKAGE BODY','PL/SQL BLOCK','VIEW','TABLE','INDEX','UNIQUE CONSTRAINT','PK CONSTRAINT','FK CONSTRAINT','CHECK CONSTRAINT','SEQUENCE','COMMENT TABLE','COMMENT COLUMN','TRIGGER'))
  ENABLE VALIDATE);

ALTER TABLE SI4_USER_SOURCE ADD (
  CONSTRAINT SI4_USER_SOURCE_PK
  PRIMARY KEY
  (NAME, TYPE)
  USING INDEX SI4_USER_SOURCE_PK
  ENABLE VALIDATE);

