ALTER TABLE SLAVES ADD (
  CONSTRAINT SLAV_STATO_CC
  CHECK (stato in ('A', 'D'))
  ENABLE VALIDATE);

ALTER TABLE SLAVES ADD (
  CONSTRAINT SLAV_PK
  PRIMARY KEY
  (DB_LINK)
  USING INDEX SLAV_PK
  ENABLE VALIDATE);

