ALTER TABLE UTENTI_STORICO ADD (
  CONSTRAINT UTES_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI_STORICO ADD (
  CONSTRAINT UTES_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX UTES_PK
  ENABLE VALIDATE);

