ALTER TABLE UTENTI_SOGGETTI_STORICO ADD (
  CONSTRAINT UTSS_OPERAZIONE_CK
  CHECK (operazione in ('I','D','BI','AI'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI_SOGGETTI_STORICO ADD (
  CONSTRAINT UTSS_PK
  PRIMARY KEY
  (ID_EVENTO)
  USING INDEX UTSS_PK
  ENABLE VALIDATE);

