ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_AMM_CK
  CHECK (amministratore in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_AMMI_INID_CC
  CHECK ((AMMINISTRATORE='N' OR AMMINISTRATORE is null) OR( AMMINISTRATORE='S' AND INFO_IDENTIFICAZIONE IS NOT NULL))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_PWD_DA_MODIFICARE
  CHECK (PWD_DA_MODIFICARE IN ('SI','NO'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_RINNOVO_PASSWORD_CC
  CHECK (
               RINNOVO_PASSWORD is null or (RINNOVO_PASSWORD in ('SI','NO')))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_TIPO_UTENTE_CC
  CHECK ( TIPO_UTENTE in ('G','U','O'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTENTI_STATO_CC
  CHECK (STATO in ('U','S','R','A'))
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_PK
  PRIMARY KEY
  (UTENTE)
  USING INDEX UTEN_PK
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_ID_UTENTE_AK
  UNIQUE (ID_UTENTE)
  USING INDEX UTEN_ID_UTENTE_AK
  ENABLE VALIDATE);

ALTER TABLE UTENTI ADD (
  CONSTRAINT UTEN_NOMINATIVO_AK
  UNIQUE (NOMINATIVO)
  USING INDEX UTEN_NOMINATIVO_AK
  ENABLE VALIDATE);

